version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.16
